#!/usr/bin/env bash
set -e

echo "Usage: ./reload [--dev]"
echo "Options:"
echo  "--dev     Run in development mode, using the test Slack channel for notifications"
echo ""

if [[ "$1" == "--dev" ]] ; then
    echo "Running in development mode"
    echo ""
fi

# Put secrets into configs
./config/configure.py $1

curl -X POST --insecure -L http://localhost/alertmanager/-/reload

curl -X POST --insecure -L http://localhost/prometheus/-/reload

# No Reload for grafana so just restart this
docker-compose -p monitor restart grafana
