#!/usr/bin/env bash
set -e

# Configure Prometheus
tmp=$(docker run -dt --rm -v prometheus_config:/data alpine)
docker cp prometheus.yml $tmp:/data/prometheus.yml
docker cp alert-rules.yml $tmp:/data/alert-rules.yml
docker kill $tmp

# Configure Alertmanager
tmp=$(docker run -dt --rm -v prometheus_alertmanager_config:/data alpine)
docker cp alertmanager.yml $tmp:/data/alertmanager.yml
docker kill $tmp

# Configure AWS metrics
./aws_metrics/create_configuration_volume.sh

docker-compose up --detach --build

echo "Now running Montagu Monitor"
echo "Browse to http://localhost:9090 to see basic output."
echo "Stop with docker-compose down"
