#!/usr/bin/env bash
set -e

echo "Usage: ./run [--dev]"
echo "Options:"
echo "--dev     Run in development mode, using the test Slack channel for notifications"
echo "          and self-signed certificate."
echo ""

if [[ "$1" == "--dev" ]] ; then
    PROFILE="dev"
else
    PROFILE="production"
fi

echo "Running in $PROFILE mode"
echo ""
echo "COMPOSE_PROFILES=$PROFILE" > .env

./config/configure.py $1
docker compose -p monitor up --detach --build

echo "Now running Montagu Monitor"
echo "Browse to http://localhost:9090 to see basic output."
