# This file configures:
# - alerts on Loki, using Prometheus rules syntax: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
# - 'recording rules' for Loki, see https://grafana.com/docs/loki/latest/alert/#recording-rules

groups:
  - name: production_rules
    interval: 1m # Query is executed every 1m
    limit: 10
    rules:
      - alert: HighPercentageError
        for: 5m
        annotations:
          grafana_base_url: ${grafana_base_url}
          error: High percentage of error logs for 5 minutes for container "{{ $labels.container_name }}" on
            host "{{ $labels.instance_hostname }}"
          playbook: https://github.com/vimc/montagu-monitor/blob/master/playbooks/HighPercentageError.md
        expr: |
          sum by (instance_hostname, container_name) (
            rate({env="production"} | detected_level = "error" [5m])
% for entry in wontfix_entries:
<% label_selector = ", ".join(f'{label["name"]}={label["value"]}' for label in entry["labels"]) %>
            unless
            rate({${label_selector}} |= ${entry["log_matcher"]} [5m])
% endfor
          )
            /
          sum by (instance_hostname, container_name) (
            rate({container_name!=""} [5m])
          )
            > 0.05
