- labels:
    container_name: barman-montagu
    instance_hostname: wpia-annex
  log_matcher: "No module named 'metrics_utils'"
- labels:
    container_name: montagu-proxy
    instance_hostname: wpia-vimc2a
  log_matcher: "No such file or directory"
