apiVersion: 1

datasources:
  - name: Prometheus
    orgId: 1

    # This ID is referenced by dashboards, which unfortunately makes it
    # difficult for us to change it to something actually unique.
    uid: my_unique_uid

    type: prometheus
    url: http://prometheus:9090/prometheus

    # Proxy requests to Prometheus through the Grafana server, instead of
    # making browsers talk directly to the Prometheus server.
    access: proxy

    # Prevent edits from the Web UI: we want all configuration to come from
    # this file.
    editable: false

    jsonData:
      # This needs to match the prometheus configuration
      # It is used to derive the $__rate_interval variable.
      timeInterval: 1m
