apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
prune: true

datasources:
  - name: Prometheus
    orgId: 1

    # This ID is referenced by dashboards, which unfortunately makes it
    # difficult for us to change it to something actually unique.
    uid: my_unique_uid

    type: prometheus
    url: http://prometheus:9090/prometheus

    # Proxy requests to Prometheus through the Grafana server, instead of
    # making browsers talk directly to the Prometheus server.
    access: proxy

    # Prevent edits from the Web UI: we want all configuration to come from
    # this file.
    editable: false

    jsonData:
      # This needs to match the prometheus configuration
      # It is used to derive the $__rate_interval variable.
      timeInterval: 1m
  
  - name: loki
    orgId: 1

    type: loki
    url: http://loki:3100

    # Proxy requests to Loki through the Grafana server, instead of
    # making browsers talk directly to the Loki server.
    access: proxy

    # Prevent edits from the Web UI: we want all configuration to come from
    # this file.
    editable: false

    jsonData: # Copied from examples at https://grafana.com/docs/grafana/latest/datasources/loki/
      timeout: 60 # Request timeout in seconds.
      # The following property is not documented: https://community.grafana.com/t/no-documentation-for-maxlines-loki-data-source/105750
      # It shows up in the grafana dashboard > connections > data sources > loki > settings > additional settings
      maxLines: 1000
