#!/usr/bin/env bash
set -ex

# Configure AWS metrics
docker volume rm aws_metrics_config || echo "No volume to remove"

./configure/configure.py > aws_configuration
tmp=$(docker run -dt --rm -v aws_metrics_config:/data alpine)
docker cp aws_configuration $tmp:/data/credentials
docker kill $tmp
rm aws_configuration

docker build --tag aws_metrics .
docker run --rm \
    -p 5000:80 \
    -v aws_metrics_config:/root/.aws  \
    aws_metrics
