global:
  slack_api_url: https://slack.com/api/chat.postMessage

route:
  receiver: 'slack'
  group_by: ['alertname']
  repeat_interval: 4h
  routes:
    - matchers:
        - frequency = high
      repeat_interval: 20m

    - matchers:
        - frequency = low
      repeat_interval: 24h

    - matchers:
        - frequency = weekly
      repeat_interval: 1w

templates:
  - 'templates/*.tmpl'

receivers:
  - name: 'slack'
    slack_configs:
      - channel: ${slack_default_channel}
        username: '{{ if eq .Status "firing" }}prometheus-sad-bot{{ else }}prometheus-happy-bot{{ end }}'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
        title: '{{ template "slack.title" .}}'
        text: '{{ template "slack.text" .}}'
        actions:
          - type: button
            text: 'Query'
            url: '{{ (index .Alerts 0).GeneratorURL }}'
          - text: 'Silence'
            type: button
            url: '{{ template "__alert_silence_link" . }}'
          # Not all alerts have an associated playbook. The button is invisible if the URL field is empty.
          - text: 'Playbook'
            type: button
            url: '{{ (index .Alerts 0).Annotations.playbook }}'
          - text: 'Docs'
            type: button
            url: 'https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-22/Monitoring'
        title_link: null
        icon_emoji: '{{ if eq .Status "firing" }}:lightning:{{ else }}:sun_with_face:{{ end }}'
        http_config:
          authorization:
            type: Bearer
            credentials: ${slack_oauth_token}
